### PR TITLE
fix: cython3.11 need regenerate them, please rm them

### PR DESCRIPTION
**Pull request by starsareintherose**

### CODE REVIEW

**Comment by endrebak** [comment]
Thanks for pushing :D. I will consider this. Why do the C files need to be removed? What problem does your PR fix?

**Comment by endrebak** [comment]
Understood. I will fix soon

**Comment by endrebak** [comment]
I fixed this and gave you credit in the changelog. I needed to bump the version and update the changelog at the same time

**Comment by endrebak** [comment]
Please tell me if it works now.

**Comment by starsareintherose** [comment]
Yeah, thanks for merging it, it works well.

**Comment by endrebak** [comment]
I'm happy to hear it :)

**Pull request closed without merging**
